"""Verification table change user_is into email

Revision ID: 0780c3b6a4ae
Revises: 9b61ac3ea1d5
Create Date: 2025-06-30 10:19:51.927670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0780c3b6a4ae'
down_revision: Union[str, Sequence[str], None] = '9b61ac3ea1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificationcode', sa.Column('email', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'verificationcode', ['email'])
    op.drop_constraint(op.f('verificationcode_user_id_fkey'), 'verificationcode', type_='foreignkey')
    op.drop_column('verificationcode', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificationcode', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('verificationcode_user_id_fkey'), 'verificationcode', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'verificationcode', type_='unique')
    op.drop_column('verificationcode', 'email')
    # ### end Alembic commands ###
