"""Email not have to be uniqe in verification table

Revision ID: 0b9762130ad3
Revises: 8a249a97235c
Create Date: 2025-07-02 15:26:19.245303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9762130ad3'
down_revision: Union[str, Sequence[str], None] = '8a249a97235c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('verificationcode_email_key'), 'verificationcode', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('verificationcode_email_key'), 'verificationcode', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
