"""Changes in archive table 

Revision ID: 8f1d33bf9e53
Revises: d3a8c9b245c5
Create Date: 2025-07-02 23:27:31.178907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1d33bf9e53'
down_revision: Union[str, Sequence[str], None] = 'd3a8c9b245c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('archivetodo_todo_id_fkey'), 'archivetodo', type_='foreignkey')
    op.drop_column('archivetodo', 'todo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetodo', sa.Column('todo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('archivetodo_todo_id_fkey'), 'archivetodo', 'todo', ['todo_id'], ['id'])
    # ### end Alembic commands ###
